stages:
  - build
  - push

variables:
  BUILDAH_ISOLATION: chroot
  STORAGE_DRIVER: vfs
  BUILD_STORAGE_DRIVER: vfs
  CONTAINER_STORAGE_DRIVER: vfs

build-workspace-image:
  stage: build
  image: quay.io/buildah/stable
  before_script:
    - dnf install -y make
  script:
    - make build-workspace-image
  artifacts:
    reports:
      dotenv: build.env
  only:
    - main

push-workspace-image:
  stage: push
  image: quay.io/buildah/stable
  before_script:
    - dnf install -y make
  script:
    - make push-workspace-image
  dependencies:
    - build-workspace-image
  only:
    - main
