stages:
  - build
  - push

variables:
  BUILDAH_ISOLATION: chroot
  STORAGE_DRIVER: vfs
  BUILD_STORAGE_DRIVER: vfs
  CONTAINER_STORAGE_DRIVER: vfs

build-workspace-image:
  stage: build
  image: quay.io/buildah/stable
  before_script:
    - dnf install -y make
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - buildah pull $CI_REGISTRY_IMAGE:latest || true
    - make build-workspace-image push-workspace-image
  # Only builds when changes are pushed to the main branch
  only:
    - main

